# Generated by Django 2.2 on 2019-04-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_adds_image_field_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(related_name='_post_related_posts_+', to='blog.Post'),
        ),
    ]
